### ISSUE TITLE
Problème aléatoire au moment du déploiement

### ISSUE THREAD

**Issue by brenard** [EsupPortail/esup-catapp-srv#8]
Je rencontre un problème aléatoire au moment du déploiement de l'application par Tomcat :

`INFO: Déploiement de l'archive /var/lib/tomcat7/webapps/catapp-services.war de l'application web
INFO 02/03/16 15:09:liquibase: Successfully acquired change log lock
INFO 02/03/16 15:09:liquibase: Reading from catapp.DATABASECHANGELOG
INFO 02/03/16 15:09:liquibase: Reading from catapp.DATABASECHANGELOG
INFO 02/03/16 15:09:liquibase: Reading from catapp.DATABASECHANGELOG
INFO 02/03/16 15:09:liquibase: Successfully released change log lock
mars 02, 2016 3:09:12 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
mars 02, 2016 3:09:12 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Erreur de démarrage du contexte [/catapp-services] suite aux erreurs précédentes
log4j:WARN No appenders could be found for logger (org.springframework.web.context.support.AnnotationConfigWebApplicationContext).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
mars 02, 2016 3:09:12 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/catapp-services] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
mars 02, 2016 3:09:12 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/catapp-services] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak.
mars 02, 2016 3:09:12 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/catapp-services] appears to have started a thread named [Health Check Thread for LDAPThreadLocalConnectionPool(serverSet=SingleServerSet(server=annuaire.ehess.fr:389))] but has failed to stop it. This is very likely to create a memory leak.
mars 02, 2016 3:09:12 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/tomcat7/webapps/catapp-services.war has finished in 6 898 ms`

L'erreur semble dûe à une configuration _log4j_ introuvable au démarage bien que le fichier _/var/lib/tomcat7/webapps/catapp-services/WEB-INF/classes/log4j.properties_ soit présent (un fois le war déployé par Tomcat) et son contenu semble tout à fait correct :

`log4j.rootLogger=DEBUG, file

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] - %m%n

log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=/var/log/tomcat7/catapp-srv.log
log4j.appender.file.MaxFileSize=5MB
log4j.appender.file.MaxBackupIndex=5
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d %p [%c] - %m%n

log4j.logger.org.esupportail.catappsrvs=DEBUG
log4j.logger.org.springframework=INFO
log4j.logger.org.hibernate=INFO`

Qui plus est, le fichier de log de l'application déclaré dans le fichier _log4j.properties_ est bien "allimenté" par l'application lors d'un démarrage en échec :

`2016-03-02 15:09:07,716 INFO [org.springframework.web.context.support.AnnotationConfigWebApplicationContext] - Refreshing Root WebApplicationContext: startup date [Wed Mar 02 15:09:07 CET 201
6]; root of context hierarchy
2016-03-02 15:09:07,841 INFO [org.springframework.web.context.support.AnnotationConfigWebApplicationContext] - Registering annotated classes: [class org.esupportail.catappsrvs.web.config.Prop
sConf]
2016-03-02 15:09:08,101 INFO [org.esupportail.catappsrvs.web.config.PropsConf$1] - Loading properties file from class path resource [properties/defaults.properties]
2016-03-02 15:09:08,103 INFO [org.esupportail.catappsrvs.web.config.PropsConf$1] - Loading properties file from file [/home/esup/portlets/esup-catapp-srv/config.properties]
2016-03-02 15:09:08,110 INFO [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2016-03-02 15:09:08,140 INFO [org.springframework.web.context.support.AnnotationConfigWebApplicationContext] - Refreshing Root WebApplicationContext: startup date [Wed Mar 02 15:09:08 CET 201
6]; root of context hierarchy
2016-03-02 15:09:08,153 INFO [org.springframework.web.context.support.AnnotationConfigWebApplicationContext] - Registering annotated classes: [class org.esupportail.catappsrvs.web.config.Prop
sConf,class org.esupportail.catappsrvs.web.config.AppConf]
2016-03-02 15:09:08,258 INFO [org.esupportail.catappsrvs.web.config.PropsConf$1] - Loading properties file from class path resource [properties/defaults.properties]
2016-03-02 15:09:08,259 INFO [org.esupportail.catappsrvs.web.config.PropsConf$1] - Loading properties file from file [/home/esup/portlets/esup-catapp-srv/config.properties]
2016-03-02 15:09:08,266 INFO [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2016-03-02 15:09:08,321 INFO [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] - Bean 'org.esupportail.catappsrvs.dao.config.Conf$JdbcDataSource
Config' of type [class org.esupportail.catappsrvs.dao.config.Conf$JdbcDataSourceConfig$$EnhancerByCGLIB$$4c282f5e] is not eligible for getting processed by all BeanPostProcessors (for example
: not eligible for auto-proxying)
2016-03-02 15:09:08,337 INFO [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] - Bean 'org.springframework.transaction.annotation.ProxyTransacti
onManagementConfiguration' of type [class org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerByCGLIB$$bfcbaf5e] is not eligible for getting processed 
by all BeanPostProcessors (for example: not eligible for auto-proxying)
2016-03-02 15:09:08,372 INFO [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] - Bean 'transactionAttributeSource' of type [class org.springfram
ework.transaction.annotation.AnnotationTransactionAttributeSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2016-03-02 15:09:08,383 INFO [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] - Bean 'transactionInterceptor' of type [class org.springframewor
k.transaction.interceptor.TransactionInterceptor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2016-03-02 15:09:08,391 INFO [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] - Bean 'org.springframework.transaction.config.internalTransactio
nAdvisor' of type [class org.springframework.transaction.interceptor.BeanFactoryTransactionAttributeSourceAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example
: not eligible for auto-proxying)
2016-03-02 15:09:08,419 INFO [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] - Bean 'JDBCDataSource' of type [class org.apache.commons.dbcp.Ba
sicDataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2016-03-02 15:09:08,422 INFO [org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] - Bean 'org.esupportail.catappsrvs.dao.config.Conf' of type [clas
s org.esupportail.catappsrvs.dao.config.Conf$$EnhancerByCGLIB$$f77f292e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2016-03-02 15:09:08,551 DEBUG [org.jboss.logging] - Logging Provider: org.jboss.logging.Log4jLoggerProvider
2016-03-02 15:09:08,575 INFO [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean] - Building JPA container EntityManagerFactory for persistence unit 'default'
2016-03-02 15:09:08,610 INFO [org.hibernate.jpa.internal.util.LogHelper] - HHH000204: Processing PersistenceUnitInfo [
        name: default
        ...]
2016-03-02 15:09:08,699 INFO [org.hibernate.Version] - HHH000412: Hibernate Core {4.3.1.Final}
2016-03-02 15:09:08,702 INFO [org.hibernate.cfg.Environment] - HHH000206: hibernate.properties not found
2016-03-02 15:09:08,704 INFO [org.hibernate.cfg.Environment] - HHH000021: Bytecode provider name : javassist
2016-03-02 15:09:08,941 INFO [org.hibernate.annotations.common.Version] - HCANN000001: Hibernate Commons Annotations {4.0.4.Final}
2016-03-02 15:09:09,036 INFO [org.hibernate.dialect.Dialect] - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
2016-03-02 15:09:09,095 INFO [org.hibernate.engine.jdbc.internal.LobCreatorBuilder] - HHH000422: Disabling contextual LOB creation as connection was null
2016-03-02 15:09:09,327 INFO [org.hibernate.hql.internal.ast.ASTQueryTranslatorFactory] - HHH000397: Using ASTQueryTranslatorFactory
2016-03-02 15:09:12,081 INFO [org.springframework.web.context.ContextLoader] - Root WebApplicationContext: initialization started
2016-03-02 15:09:12,081 INFO [org.springframework.web.context.ContextLoader] - Root WebApplicationContext: initialization completed in 0 ms`

Un simple _touch_ sur le fichier WAR _/var/lib/tomcat7/webapps/catapp-services.war_ pour redéclencher le déploiement de l'application par Tomcat permet de régler le problème (rarement forcément du premier coup)  : l'application est rédéployée et démarre noramlement :

`INFO: Déploiement de l'archive /var/lib/tomcat7/webapps/catapp-services.war de l'application web
INFO 02/03/16 15:11:liquibase: Successfully acquired change log lock
INFO 02/03/16 15:11:liquibase: Reading from catapp.DATABASECHANGELOG
INFO 02/03/16 15:11:liquibase: Reading from catapp.DATABASECHANGELOG
INFO 02/03/16 15:11:liquibase: Reading from catapp.DATABASECHANGELOG
INFO 02/03/16 15:11:liquibase: Successfully released change log lock
mars 02, 2016 3:11:58 PM org.glassfish.jersey.server.ApplicationHandler initialize
INFO: Initiating Jersey application, version Jersey: 2.5.1 2014-01-02 13:43:00...
mars 02, 2016 3:11:59 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/tomcat7/webapps/catapp-services.war has finished in 7 120 ms`

Le fichier de log de l'application (déclaré dans le fichier _log4j.properties_) ne montre en outre aucune différence entre un démarrage fonctionnel ou non.

Je ne rencontre ce problème avec aucune des autres applications hébergées par ce Tomcat (que se soit _catapp-admin_ ou d'autres applications).

Merci d'avance pour votre aide.

**Comment by gneuvill** [comment]
Je pense plutôt que le warning log4j n'est qu'une conséquence de l'échec du démarrage du contexte spring.

Pourriez-vous poster tout le contenu du catalina.out de tomcat (et particulièrement les lignes précédant celle-ci : "Erreur de démarrage du contexte [/catapp-services] suite aux erreurs précédentes") ?

**Comment by brenard** [comment]
Pour le coup j'ai rien de plus dans le fichier de log _catalina.out_ que ce que je vous ai déjà mis ici :
`[...]
INFO: Deployment of web application archive /var/lib/tomcat7/webapps/catapp-admin.war has finished in 7 604 ms
mars 02, 2016 7:21:55 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Déploiement de l'archive /var/lib/tomcat7/webapps/catapp-services.war de l'application web
INFO 02/03/16 19:22:liquibase: Successfully acquired change log lock
INFO 02/03/16 19:22:liquibase: Reading from catapp.DATABASECHANGELOG
INFO 02/03/16 19:22:liquibase: Reading from catapp.DATABASECHANGELOG
INFO 02/03/16 19:22:liquibase: Reading from catapp.DATABASECHANGELOG
INFO 02/03/16 19:22:liquibase: Successfully released change log lock
mars 02, 2016 7:22:02 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
mars 02, 2016 7:22:02 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Erreur de démarrage du contexte [/catapp-services] suite aux erreurs précédentes
log4j:WARN No appenders could be found for logger (org.springframework.web.context.support.AnnotationConfigWebApplicationContext).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
mars 02, 2016 7:22:02 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/catapp-services] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
mars 02, 2016 7:22:02 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/catapp-services] appears to have started a thread named [Health Check Thread for LDAPThreadLocalConnectionPool(serverSet=SingleServerSet(server=annuaire.ehess.fr:389))] but has failed to stop it. This is very likely to create a memory leak.
mars 02, 2016 7:22:02 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/catapp-services] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak.
mars 02, 2016 7:22:02 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/tomcat7/webapps/catapp-services.war has finished in 7 056 ms
mars 02, 2016 7:22:02 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Déploiement du répertoire /var/lib/tomcat7/webapps/esup-helpdeskviewer de l'application web
[...]`

Comme vous pouvez le voir, avant il s'agit d'un déploiement d'un autre appli et après également.

Autre extrait exhaustif en cas d'un deploy via un _touch_ du fichier WAR :
`mars 02, 2016 7:27:44 PM org.apache.catalina.startup.HostConfig undeploy
INFO: Repli (undeploy) de l'application web ayant pour chemin de contexte /catapp-services
mars 02, 2016 7:27:44 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Déploiement de l'archive /var/lib/tomcat7/webapps/catapp-services.war de l'application web
INFO 02/03/16 19:27:liquibase: Successfully acquired change log lock
INFO 02/03/16 19:27:liquibase: Reading from catapp.DATABASECHANGELOG
INFO 02/03/16 19:27:liquibase: Reading from catapp.DATABASECHANGELOG
INFO 02/03/16 19:27:liquibase: Reading from catapp.DATABASECHANGELOG
INFO 02/03/16 19:27:liquibase: Successfully released change log lock
mars 02, 2016 7:27:50 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
mars 02, 2016 7:27:50 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Erreur de démarrage du contexte [/catapp-services] suite aux erreurs précédentes
log4j:WARN No appenders could be found for logger (org.springframework.web.context.support.AnnotationConfigWebApplicationContext).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
mars 02, 2016 7:27:50 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/catapp-services] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
mars 02, 2016 7:27:50 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/catapp-services] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak.
mars 02, 2016 7:27:50 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/catapp-services] appears to have started a thread named [Health Check Thread for LDAPThreadLocalConnectionPool(serverSet=SingleServerSet(server=annuaire.ehess.fr:389))] but has failed to stop it. This is very likely to create a memory leak.
mars 02, 2016 7:27:50 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/tomcat7/webapps/catapp-services.war has finished in 6 693 ms`

Le premier extrait fait suite à un restart de Tomcat et le second à un _touch_ du WAR donc. Pour ce dernier essai, j'ai du faire deux _touch_ pour que l'application démarre correctement. Une fois déployée, elle est très stable par contre (aucun problème aléatoire).

**Comment by gneuvill** [comment]
Ben là... Je sèche ! Ceci dit, de mémoire, chacune des applications (catapp-admin|services) prend comme paramètres au démarrage "-Dconfig.location" et "-Dlog4j.location" qui indiquent respectivement l'emplacement du fichier de config principal et celui de la conf de logging.

Étant donné qu'il s'agit de paramètres système, il n'est pas possible de les passer deux fois pour le lancement d'un seul tomcat (et donc d'une seule jvm). Autrement dit, on a pas prévu le déploiement de ces deux applications dans le même tomcat.

Pourriez-vous essayer en déployant chacune des applis dans son propre tomcat ?

**Comment by brenard** [comment]
Effectivement, je me suis confronté au paramètre  "-Dconfig.location" commun au deux applications mais pour résoudre le problème, j'ai changé le nom de la directive dans les deux applications (dans le fichier "src/main/java/org/esupportail/catappsrvs/web/config/PropsConf.java") pour les différencier. Je précise que c'est m'a seule modif dans le code livré.

Concernant le contenu de ces fichiers de configuration, et notamment celui de catapp-services, je ne vois pas d'informations concernant le chemin de la configuration de logging. Quel directive contrôle le positionnement de ce fichier de configuration ? Plus globalement, connaissez-vous le processus de "démarrage" de log4j ? Que cherche t-il, à quel endroit, et en fonction de quels paramètres pour que je puisse essayer de "remonter" le problème ?

Concernant le déploiement de l'application sur un autre tomcat, je peut essayer mais j'avais le problème avant même de déployer catapp-admin sur ce même tomcat... Pas sûr que ce soit concluant...

**Comment by gneuvill** [comment]
- "-Dlog4j.configuration" pour indiquer à log4j l'emplacement de son fichier de conf
- "-Dlog4j.debug" pour mettre log4j lui-même en debug sur la sortie standard (catalina.out dans tomcat)

En quelle version de catapp-srvs êtes-vous ?

**Comment by brenard** [comment]
> "-Dlog4j.configuration" pour indiquer à log4j l'emplacement de son fichier de conf

Cette directive impacte t'elle uniquement l'application catapp-srv ou il s'agit d'un paramètre global ? car je ne voudrais pas impacter les autres applications hébergées sur le même tomcat.. Il n'existe pas un paramètre à mettre dans le fichier de configuration de l'appli ?

> "-Dlog4j.debug" pour mettre log4j lui-même en debug sur la sortie standard (catalina.out dans tomcat)

Ok, ça je peut tester sans trop de problème, faut juste que je programme un restart de Tomcat. Merci !

> En quelle version de catapp-srvs êtes-vous ?

En 0.1.9, commit 7aba467ff3a6254f0860b20db2a68fb91370f366

**Comment by gneuvill** [comment]
Toutes les directives commençant par "-D" correspondent à des paramètres JVM, dont affectant toutes les applications tournant sur l'instance de celle-ci (i.e dans votre cas, tomcat + toutes les webapps qu'il propulse). Mais je pense vraiment qu'il serait plus simple et sûr de faire tourner chaque appli dans son propre tomcat...

> En 0.1.9, commit 7aba467

Bien, donc ce n'est donc pas lié au passage du code à java 8. À propos, quelles versions de la jvm et de tomcat utilisez-vous ?

**Comment by brenard** [comment]
Pas simple de faire un test avec les applis sur des serveurs différents sur l'infra utilisée jusqu'ici, j'ai donc redéployé les applis sur notre infra de tests.
Je reproduit le problème sur cette infra en déployant les deux applications sur le même serveur (même erreur log4j remontée) mais je n'ai plus ce problème en déployant l'application esup-catapp-services sur un autre serveur que esup-catapp-admin bien que cet autre serveur soit installé à l'identique.

L'infra principale, comme celle de tests, est en Debian Jessie, Tomcat 7.0.28 et JDK 1.7.0_17.

**Comment by gneuvill** [comment]
M'en doutais... Du coup, comme solution définitive, je ne vois que le déploiement systématique de chaque application dans son propre conteneur de servlet, en test comme en prod. Vous allez dire que ça n'explique pas la cause du problème et vous aurez raison, mais je répondrais par un "bienvenue dans le monde java, ses variables et ses effets de bord non contrôlés !", ce qui veut dire que je n'essaierai pas plus avant de débrouiller l'indébrouillable (qui est le coupable entre tomcat, le modèle de servlet, spring, jersey ou log4j => tous ! D'ailleurs, pour une future version de catapp, je compte bien dégraisser considérablement le mammouth en m'appuyant sur https://ratpack.io/).

Merci de vos retours en tout cas. Je peux clore le ticket ?
